### ISSUE TITLE
Tables screw up responsiveness

### ISSUE THREAD

**Issue by neiljohari** [Syosset/Web#12]
Example: https://syosseths.com/departments/math

**Comment by neiljohari** [comment]
TinyMCE needs to add bootstrap class

```
tinymce.init({
    table_default_attributes: {
        class: 'myclassname'
    }
});
```

**Comment by JinxuanCang** [comment]
We could use CSS native grid system, but I have to confess that is less browser capability due to only a few browsers support it.

**Comment by JinxuanCang** [comment]
I over complicated the situation. No CSS grid system is required just use display instead. Check this out: [](http://php-campus-jinxuancang406559.codeanyapp.com/css_grid.html)
