### ISSUE TITLE
Activities Page: Use XHR(AJAX) to turn the page

### ISSUE THREAD

**Issue by JinxuanCang** [Syosset/Web#29]
Reloading the entire web page to turn the list page is inefficient. I highly recommend use XHR GET method to pull down list data from the server resources. In the future, all the forms and tables should be submitted, responded and refreshed via the XHR.

**Comment by kailan** [comment]
Our use of [Turbolinks](https://github.com/turbolinks/turbolinks) prevents the entire page from having to be reloaded and re-rendered, making the work needed to implement XHR/AJAX requests for data updates unnecessary.
